import json
import requests

REMOTE_TS_API_ADDRESS = 'https://api.testsavant.ai'

REQUEST_JSON = """
{
    "prompt": "{PROMPT}",
    "config": {
        "project_id": "{PROJECT_ID}",
        "fail_fast": true,
        "cache": {
            "enabled": true,
            "ttl": 3600
        }
    },
    "use": [{SCANNERS}],
}
""".replace('\n', ' ')

class Scanner:
    
    def __init__(self, name, type, params={}):
        self.name = name
        self.type = type
        self.params = params
    
    def to_json(self):
        params = json.dumps(self.params)
        return f'{{"name": "{self.name}", "type": "{self.type}", "params": {params}}}'

    def to_dict(self):
        return {
            "name": self.name,
            "type": self.type,
            "params": self.params
        }

class TSGuard:
    
    def __init__(self, API_KEY, PROJECT_ID, scan_mode = "input", remote_addr=REMOTE_TS_API_ADDRESS, fail_fast=True):
        """        
        scan_mode : str
            "input": analyzes prompts sent to the llm
            "output": analyzes responses generated by the llm
        
        remote_addr : str, optional
            Base URL for the remote API endpoint.
            Default is https://api.testsavant.ai
        """
        self.API_KEY = API_KEY
        self.PROJECT_ID = PROJECT_ID
        self.fail_fast = fail_fast
        self.scanners = []
        if scan_mode not in ["input", "output"]:
            raise ValueError(f"scan_mode must be either 'input' or 'output', got '{scan_mode}'")
        if scan_mode == "input":
            self.remote_addr = remote_addr + '/guard/prompt'
        if scan_mode == "output":
            self.remote_addr = remote_addr + '/guard/output'

    def add_scanner(self, scanner):
        self.scanners.append(scanner)
        
    def scan(self, prompt):
        # replace placeholders in the request json
        request_body = self._prepare_request_json(prompt, self.PROJECT_ID, self.scanners)
        # make the request
        response = requests.post(
            self.remote_addr,
            headers={
                'x-api-key': self.API_KEY,
                'Content-Type': 'application/json'
            },
            data=json.dumps(request_body)
        )
        if response.status_code != 200:
            raise Exception(f"Request failed with status code {response.status_code}")
        return response.json()

    def _prepare_request_json(self, prompt, project_id, scanners):
        req_dict = {
            "prompt": prompt,
            "config": {
                "project_id": project_id,
                "fail_fast": self.fail_fast,
                "cache": {
                    "enabled": True,
                    "ttl": 3600
                }  
            },
            "use": [scanner.to_dict() for scanner in scanners]
        }
        return req_dict
